# Generated by Django 5.0.7 on 2024-07-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка для оплаты",
                max_length=400,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="ID сессии для оплаты",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
    ]
